sonar.projectKey=Local_Authority_Verifier
sonar.projectName=Local_Authority_Verifier
sonar.projectVersion=1.0
sonar.organization=chiranthdv

sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/tests/**,**/coverage/**,**/dist/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
